services:
  telegram-bot:
    build: .
    container_name: reminder_bot
    env_file: .env
    volumes:
      - bot-data:/app/data
      - bot-models:/app/models
    restart: unless-stopped

volumes:
  bot-data:
  bot-models:
