services:
  telegram-bot:
    build: .
    container_name: reminder_bot
    env_file: .env
    volumes:
      - data-volume:/app/data
      - model-volume:/app/models
    restart: unless-stopped

volumes:
  data-volume:
    driver: local
  model-volume:
    driver: local
